# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mb_subsystem/mb_subsystem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem || ORIG_REF_NAME==mb_subsystem} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_mig_7series_0_0 || ORIG_REF_NAME==mb_subsystem_mig_7series_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/mb_subsystem_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/mb_subsystem_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_uartlite_0_0 || ORIG_REF_NAME==mb_subsystem_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_0/mb_subsystem_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_gpio_0_0 || ORIG_REF_NAME==mb_subsystem_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_proc_sys_reset_0_0/mb_subsystem_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_proc_sys_reset_0_0 || ORIG_REF_NAME==mb_subsystem_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_0/mb_subsystem_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_bram_ctrl_0_0 || ORIG_REF_NAME==mb_subsystem_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/mb_subsystem_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_v10_0 || ORIG_REF_NAME==mb_subsystem_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_0/mb_subsystem_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_v10_0 || ORIG_REF_NAME==mb_subsystem_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_dlmb_bram_if_cntlr_0/mb_subsystem_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_subsystem_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_ilmb_bram_if_cntlr_0/mb_subsystem_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_subsystem_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_lmb_bram_0/mb_subsystem_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_lmb_bram_0 || ORIG_REF_NAME==mb_subsystem_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_lmb_v10_0/mb_subsystem_lmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_lmb_v10_0 || ORIG_REF_NAME==mb_subsystem_lmb_v10_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/mb_subsystem_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_mdm_1_0 || ORIG_REF_NAME==mb_subsystem_mdm_1_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_bram_0/mb_subsystem_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==mb_subsystem_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/mb_subsystem_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_axi_smc_0 || ORIG_REF_NAME==mb_subsystem_axi_smc_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_xbar_0/mb_subsystem_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_xbar_0 || ORIG_REF_NAME==mb_subsystem_xbar_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_microblaze_0_axi_periph_0/mb_subsystem_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_subsystem_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_subsystem/ip/mb_subsystem_system_ila_0/mb_subsystem_system_ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_subsystem_system_ila_0 || ORIG_REF_NAME==mb_subsystem_system_ila_0} -quiet] -quiet

# XDC: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/mb_subsystem_ooc.xdc
