# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/mb_subsystem_system_ila_0.xci
# IP: The module: 'mb_subsystem_system_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/bd_6c65.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65 || ORIG_REF_NAME==bd_6c65} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_0/bd_6c65_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_ila_lib_0 || ORIG_REF_NAME==bd_6c65_ila_lib_0} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_1/bd_6c65_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_g_inst_0 || ORIG_REF_NAME==bd_6c65_g_inst_0} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_2/bd_6c65_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_slot_0_aw_0 || ORIG_REF_NAME==bd_6c65_slot_0_aw_0} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_3/bd_6c65_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_slot_0_w_0 || ORIG_REF_NAME==bd_6c65_slot_0_w_0} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_4/bd_6c65_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_slot_0_b_0 || ORIG_REF_NAME==bd_6c65_slot_0_b_0} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_5/bd_6c65_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_slot_0_ar_0 || ORIG_REF_NAME==bd_6c65_slot_0_ar_0} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_6/bd_6c65_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_slot_0_r_0 || ORIG_REF_NAME==bd_6c65_slot_0_r_0} -quiet] -quiet

# XDC: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6c65_ila_lib_0 || ORIG_REF_NAME==bd_6c65_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6c65_ila_lib_0 || ORIG_REF_NAME==bd_6c65_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_0/bd_6c65_ila_lib_0_ooc.xdc

# XDC: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/bd_6c65_ooc.xdc

# XDC: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/mb_subsystem_system_ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_subsystem_system_ila_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.srcs/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/mb_subsystem_system_ila_0.xci
# IP: The module: 'mb_subsystem_system_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/bd_6c65.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65 || ORIG_REF_NAME==bd_6c65} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_0/bd_6c65_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_ila_lib_0 || ORIG_REF_NAME==bd_6c65_ila_lib_0} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_1/bd_6c65_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_g_inst_0 || ORIG_REF_NAME==bd_6c65_g_inst_0} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_2/bd_6c65_slot_0_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_slot_0_aw_0 || ORIG_REF_NAME==bd_6c65_slot_0_aw_0} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_3/bd_6c65_slot_0_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_slot_0_w_0 || ORIG_REF_NAME==bd_6c65_slot_0_w_0} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_4/bd_6c65_slot_0_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_slot_0_b_0 || ORIG_REF_NAME==bd_6c65_slot_0_b_0} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_5/bd_6c65_slot_0_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_slot_0_ar_0 || ORIG_REF_NAME==bd_6c65_slot_0_ar_0} -quiet] -quiet

# IP: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_6/bd_6c65_slot_0_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_6c65_slot_0_r_0 || ORIG_REF_NAME==bd_6c65_slot_0_r_0} -quiet] -quiet

# XDC: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6c65_ila_lib_0 || ORIG_REF_NAME==bd_6c65_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6c65_ila_lib_0 || ORIG_REF_NAME==bd_6c65_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_0/bd_6c65_ila_lib_0_ooc.xdc

# XDC: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/bd_6c65_ooc.xdc

# XDC: /home/r-yamashita/bootLoader/MicroBlaze-Tutorial/microblaze_tutorial_sp701/microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ip/mb_subsystem_system_ila_0/mb_subsystem_system_ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_subsystem_system_ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
