#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Script generated by Vivado on Thu Jun 01 19:49:02 JST 2023
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# Tool Version Limit: 2023.05 
#
# Filename     : mb_subsystem.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : mb_subsystem.sh
#                mb_subsystem.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                mb_subsystem.sh [-reset_run]
#                mb_subsystem.sh [-reset_log]
#                mb_subsystem.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the Xilinx simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'mb_subsystem.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname xil_defaultlib -libname microblaze_v11_0_11 -libname axi_lite_ipif_v3_0_4 -libname lib_pkg_v1_0_2 -libname lib_srl_fifo_v1_0_2 -libname lib_cdc_v1_0_2 -libname axi_uartlite_v2_0_32 -libname interrupt_control_v3_1_4 -libname axi_gpio_v2_0_30 -libname proc_sys_reset_v5_0_13 -libname axi_bram_ctrl_v4_1_8 -libname lmb_v10_v3_0_12 -libname lmb_bram_if_cntlr_v4_0_22 -libname blk_mem_gen_v8_4_6 -libname mdm_v3_2_24 -libname xlconstant_v1_1_7 -libname smartconnect_v1_0 -libname axi_infrastructure_v1_1_0 -libname axi_register_slice_v2_1_28 -libname axi_vip_v1_1_14 -libname generic_baseblocks_v2_1_0 -libname fifo_generator_v13_2_8 -libname axi_data_fifo_v2_1_27 -libname axi_crossbar_v2_1_29 -libname gigantic_mux -libname xlconcat_v2_1_4 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm xil_defaultlib microblaze_v11_0_11 axi_lite_ipif_v3_0_4 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_uartlite_v2_0_32 interrupt_control_v3_1_4 axi_gpio_v2_0_30 proc_sys_reset_v5_0_13 axi_bram_ctrl_v4_1_8 lmb_v10_v3_0_12 lmb_bram_if_cntlr_v4_0_22 blk_mem_gen_v8_4_6 mdm_v3_2_24 xlconstant_v1_1_7 smartconnect_v1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_28 axi_vip_v1_1_14 generic_baseblocks_v2_1_0 fifo_generator_v13_2_8 axi_data_fifo_v2_1_27 axi_crossbar_v2_1_29 gigantic_mux xlconcat_v2_1_4)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "mb_subsystem.sh - Script generated by export_simulation (Vivado v2023.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./mb_subsystem.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "/tools/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/tools/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm -V93 $xmvhdl_opts \
  "/tools/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_addr_decode.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_read.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg_bank.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_top.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_write.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_ar_channel.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_aw_channel.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_b_channel.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_arbiter.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_fsm.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wr_cmd_fsm.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_translator.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_incr_cmd.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_r_channel.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_simple_fifo.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_fifo.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_w_channel.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wrap_cmd.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_a_upsizer.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_register_slice.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_upsizer.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_axic_register_slice.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_and.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_and.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_or.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_or.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_command_fifo.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel_static.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_r_upsizer.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/axi/mig_7series_v4_2_ddr_w_upsizer.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_clk_ibuf.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_infrastructure.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_iodelay_ctrl.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v4_2_tempmon.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_arb_mux.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_arb_row_col.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_arb_select.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_cntrl.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_common.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_compare.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_mach.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_queue.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_bank_state.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_col_mach.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_mc.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_rank_cntrl.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_rank_common.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_rank_mach.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/controller/mig_7series_v4_2_round_robin_arb.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_buf.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_dec_fix.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_gen.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_merge_enc.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v4_2_fi_xor.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_2_mem_intfc.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v4_2_memc_ui_top_axi.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_group_io.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_lane.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_tempmon.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_calib_top.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_skip_calib_tap.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_if_post_fifo.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_of_pre_fifo.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_4lanes.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_init.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_rdlvl.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_top.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrcal.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_prbs_gen.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_top.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_data.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_pd.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_tap_base.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_meta.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_edge_store.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/phy/mig_7series_v4_2_poc_cc.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_cmd.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_rd_data.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_top.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/ui/mig_7series_v4_2_ui_wr_data.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/mb_subsystem_mig_7series_0_0_mig_sim.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mig_7series_0_0/mb_subsystem_mig_7series_0_0/user_design/rtl/mb_subsystem_mig_7series_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work microblaze_v11_0_11 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/e224/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/mb_subsystem/ip/mb_subsystem_microblaze_0_0/sim/mb_subsystem_microblaze_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_pkg_v1_0_2 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_srl_fifo_v1_0_2 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_uartlite_v2_0_32 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/3dd9/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_uartlite_0_0/sim/mb_subsystem_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work interrupt_control_v3_1_4 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_gpio_v2_0_30 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/18b7/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_gpio_0_0/sim/mb_subsystem_axi_gpio_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_13 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/mb_subsystem/ip/mb_subsystem_proc_sys_reset_0_0/sim/mb_subsystem_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_bram_ctrl_v4_1_8 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/85f5/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_0/sim/mb_subsystem_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_v10_v3_0_12 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/cd1d/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/mb_subsystem/ip/mb_subsystem_dlmb_v10_0/sim/mb_subsystem_dlmb_v10_0.vhd" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_ilmb_v10_0/sim/mb_subsystem_ilmb_v10_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_bram_if_cntlr_v4_0_22 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/b87e/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/mb_subsystem/ip/mb_subsystem_dlmb_bram_if_cntlr_0/sim/mb_subsystem_dlmb_bram_if_cntlr_0.vhd" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_ilmb_bram_if_cntlr_0/sim/mb_subsystem_ilmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_6 $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/bb55/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_lmb_bram_0/sim/mb_subsystem_lmb_bram_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/mb_subsystem/ip/mb_subsystem_lmb_v10_0/sim/mb_subsystem_lmb_v10_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work mdm_v3_2_24 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/4e42/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/mb_subsystem/ip/mb_subsystem_mdm_1_0/sim/mb_subsystem_mdm_1_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_bram_ctrl_0_bram_0/sim/mb_subsystem_axi_bram_ctrl_0_bram_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_7 $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/b0f2/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_0/sim/bd_f2d6_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_1/sim/bd_f2d6_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_2/sim/bd_f2d6_arsw_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_3/sim/bd_f2d6_rsw_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_4/sim/bd_f2d6_awsw_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_5/sim/bd_f2d6_wsw_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_6/sim/bd_f2d6_bsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/be1f/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_7/sim/bd_f2d6_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_8/sim/bd_f2d6_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/637d/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_9/sim/bd_f2d6_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f38e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_10/sim/bd_f2d6_s00a2s_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_11/sim/bd_f2d6_sarn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_12/sim/bd_f2d6_srn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_13/sim/bd_f2d6_sawn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_14/sim/bd_f2d6_swn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_15/sim/bd_f2d6_sbn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_16/sim/bd_f2d6_s01mmu_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_17/sim/bd_f2d6_s01tr_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_18/sim/bd_f2d6_s01sic_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_19/sim/bd_f2d6_s01a2s_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_20/sim/bd_f2d6_sarn_1.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_21/sim/bd_f2d6_srn_1.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_22/sim/bd_f2d6_s02mmu_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_23/sim/bd_f2d6_s02tr_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_24/sim/bd_f2d6_s02sic_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_25/sim/bd_f2d6_s02a2s_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_26/sim/bd_f2d6_sarn_2.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_27/sim/bd_f2d6_srn_2.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_28/sim/bd_f2d6_sawn_1.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_29/sim/bd_f2d6_swn_1.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_30/sim/bd_f2d6_sbn_1.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/9cc5/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_31/sim/bd_f2d6_m00s2a_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_32/sim/bd_f2d6_m00arn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_33/sim/bd_f2d6_m00rn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_34/sim/bd_f2d6_m00awn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_35/sim/bd_f2d6_m00wn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_36/sim/bd_f2d6_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/6bba/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_37/sim/bd_f2d6_m00e_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_38/sim/bd_f2d6_m01s2a_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_39/sim/bd_f2d6_m01arn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_40/sim/bd_f2d6_m01rn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_41/sim/bd_f2d6_m01awn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_42/sim/bd_f2d6_m01wn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_43/sim/bd_f2d6_m01bn_0.sv" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/ip/ip_44/sim/bd_f2d6_m01e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/bd_0/sim/bd_f2d6.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/87d1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_14 $xmvlog_opts -sv +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ed63/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_axi_smc_0/sim/mb_subsystem_axi_smc_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_8 $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/c97d/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_8 -V93 $xmvhdl_opts \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_8 $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_27 $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/fab7/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_29 $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f8f3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_xbar_0/sim/mb_subsystem_xbar_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_0/sim/bd_6c65_ila_lib_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work gigantic_mux $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/e87a/hdl/gigantic_mux_v1_0_cntr.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_1/bd_6c65_g_inst_0_gigantic_mux.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_1/sim/bd_6c65_g_inst_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlconcat_v2_1_4 $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"$ref_dir/../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/f0b6/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/66be/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/ec67/hdl" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/1b7e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/122e/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/affe/hdl/verilog" +incdir+"../../../../microblaze_tutorial_sp701.gen/sources_1/bd/mb_subsystem/ipshared/20d0/hdl/verilog" +incdir+"/tools/Xilinx/Vivado/2023.1/data/xilinx_vip/include" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_2/sim/bd_6c65_slot_0_aw_0.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_3/sim/bd_6c65_slot_0_w_0.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_4/sim/bd_6c65_slot_0_b_0.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_5/sim/bd_6c65_slot_0_ar_0.v" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/ip/ip_6/sim/bd_6c65_slot_0_r_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/mb_subsystem/ip/mb_subsystem_system_ila_0/bd_0/sim/bd_6c65.vhd" \
  "../../../bd/mb_subsystem/ip/mb_subsystem_system_ila_0/sim/mb_subsystem_system_ila_0.vhd" \
  "../../../bd/mb_subsystem/sim/mb_subsystem.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.mb_subsystem xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.mb_subsystem -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path != "") && !(-e $lib_map_path) ]]; then
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log mb_subsystem_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./mb_subsystem.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: mb_subsystem.sh [-help]\n\
Usage: mb_subsystem.sh [-step]\n\
Usage: mb_subsystem.sh [-lib_map_path]\n\
Usage: mb_subsystem.sh [-reset_run]\n\
Usage: mb_subsystem.sh [-reset_log]\n\
Usage: mb_subsystem.sh [-keep_index]\n\
Usage: mb_subsystem.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
